#!/bin/bash

lxc exec feeluniqueDev -- /mnt/lxc/chef/installChef
lxc exec feeluniqueDev -- /mnt/lxc/chef/doProvision

# Set permissions
lxc exec feeluniqueDev -- setfacl -Rm ubuntu:rw /mnt
lxc exec feeluniqueDev -- setfacl -Rm www-data:rw /mnt
lxc exec feeluniqueDev -- setfacl -d -Rm ubuntu:rwx /mnt
lxc exec feeluniqueDev -- setfacl -d -Rm www-data:rwx /mnt
